---
language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
# install:
#  - ./release.sh
# command to run tests
script: ./build.sh
notifications:
  email:
    - lowell@kintyre.co
