name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python-version: [2.7, 3.7]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kintyre-splunk-conf==v0.8-beta5
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: ksconf package build
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pwd
        ls -al
        git status
        git tag
        ./release.sh
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
